blank_issues_enabled: false
contact_links:
  - name: Website
    url: https://justacdn.rocks/
    about: Our website.
  - name: Documentation
    url: https://docs.justacdn.rocks/
    about: Our documentation.
  - name: Bugs
    url: https://github.com/justacdn/bugs
    about: Here you can report bugs found on justacdn.rocks platforms.
